name: gassho
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.6
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  just_audio: ^0.9.36
  jwt_decoder: ^2.0.1
  path_provider: ^2.1.2
  pod_player: ^0.2.1
  video_player: ^2.8.2
  vimeo_player_flutter: ^0.1.0
  webview_flutter: ^4.5.0
  onesignal_flutter: ^3.2.7
  ip_country_lookup: ^1.0.2
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  

