name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.1
  chewie: ^1.7.4
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.6
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  just_audio: ^0.9.36
  jwt_decoder: ^2.0.1
  path_provider: ^2.1.2
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

    - assets/music/

    - assets/video/mov_bbb.mp4

  

